### ISSUE TITLE
Resuming fuzzing

### ISSUE THREAD

**Issue by marcinguy** [ttdennis/fpicker#12]
What is the best practice to resume fuzzing?

Thanks,

**Comment by ttdennis** [comment]
In standalone mode newly discovered corpus files are stored in the input directory. If you want to resume fuzzing from where the fuzzer last stopped, you would start it with the last seed that was used during the previous fuzzing session (using the `--seed` parameter).

In AFL mode, AFL pretty much handles everything resumption-related.

**Comment by marcinguy** [comment]
I have noticed it reads the coverage and corpus from output directory automatically upon subsequent start. But this is something different, right? 

Is --seed taking a directory parameter? Or just appending --seed would do it
