### ISSUE TITLE
Not tracking edge coverage properly

### ISSUE THREAD

**Issue by hgarrereyn** [ttdennis/fpicker#15]
This line does not update `prev_cov` in the `user_data` struct so `prev_cov` is always 0 and AFL bits are computed only on the target address:
https://github.com/ttdennis/fpicker/blob/main/harness/stalker-instrumentation.js#L62

It probably should be `ud->prev_loc = cur_loc >> 1;`

**Comment by ttdennis** [comment]
Oh wow. Thanks! Good Catch.
