### ISSUE TITLE
stability issue

### ISSUE THREAD

**Issue by vanhauser-thc** [ttdennis/fpicker#2]
ensure that you reset `prev_loc` to zero for every fuzz attempt, as otherwise the first edge ID calculated is always different, resulting in "new paths" being found that are not.

**Comment by ttdennis** [comment]
Thanks for the advice!

**Comment by vanhauser-thc** [comment]
is the stability now 100% or did it just slightly improve?

**Comment by vanhauser-thc** [comment]
Also you read the fuzz data from stdin, correct? There is also the feature of shared memory fuzz data. the forksever in fpicker only has to set a specific bit on the intial status sent and map the shmem for it (from its specific env var). this is quite faster and has no kernel overhead. the length of a specific fuzz case is in the first 4 byte of the memory, and the memory size is MAX_FILE + 4.
