### ISSUE TITLE
Building and running on Android

### ISSUE THREAD

**Issue by p2h5** [ttdennis/fpicker#20]
Hello,

currently I am trying to get fpicker to run on Android devices.
I already tried to do it like in the issues https://github.com/ttdennis/fpicker/issues/19 and https://github.com/ttdennis/fpicker/issues/5, but did not succeded.
As this is not featured in the docs yet, I wanted to (1) ask about some help on building and running it and (2) use this issue as a base to update the docs for running fpicker on Android devices.

First, I wanted to ask, which frida-core-devkit to download. Is frida-core-devkit-16.0.2-android-arm64.tar.xz the right one? Or can I use 
frida-core-devkit-16.0.2-linux-arm64.tar.xz as well?

I tried both of them and added the header file and the library as frida-core-linux.h and libfrida-core-linux.a to the fpicker root.
After that, I simply tried to run `make fpicker-linux`.
Unfortunately I ran with both of them in the following error:
`cannot find -lfrida-core-linux: No such file or directory`
As I am not really fluent with C, I am not sure, if this error is trivial or I am missing something.

I would be really thankful for any input and would like to update the README with detailed instructions for running on Android, as this seems to be an often asked request. (At least as seen in https://github.com/ttdennis/fpicker/issues/5)

**Comment by ttdennis** [comment]
Hey, maybe you have already seen it, but you could take a look at https://github.com/marcinguy/fpicker-aflpp-android/ :)

**Comment by colonnac** [comment]
Guys @marcinguy disappeared.
Did someone cloned its project?

It would be highly valuable to have back its code as there's not a lot about fuzzing on android processes with AFL++
