### ISSUE TITLE
Network device fuzzing with afl++ mode

### ISSUE THREAD

**Issue by marcinguy** [ttdennis/fpicker#6]
Hi,

So I have to put the Frida Server on the mobile, do port forwarding and then run fpicker

Assuming I have test-network binary on the phone

This is what I should run:

```
afl-fuzz -i examples/test-network/in -o ./examples/test-network/out -- \\
    ./fpicker --fuzzer-mode afl -e attach -p test-network -D remote -f ./examples/test-network/harness.js
```

Thanks,

**Comment by ttdennis** [comment]
I hope my [answer](https://github.com/ttdennis/fpicker/issues/5#issuecomment-826367555) in #5 should cover that as well. In general: AFL++ mode only works on a local device (i.e., not in network or USB mode)
