### ISSUE TITLE
Fields explanation

### ISSUE THREAD

**Issue by marcinguy** [ttdennis/fpicker#9]
Can you briefly explain the fields meaning?

`[t=1619610289] [BBs=1567] [seed=795] [fc=1591] [fcps=13] [cur_loop=105957] [mut_avg=2] [cov_avg=59723] [corpus=2]`

Also how a "healthy" fuzzing output should look like?

I assume corpus increasing etc?

Thanks,

**Comment by ttdennis** [comment]
Ah, good question. It's something I could put into the Readme...

- `t`: the current timestamp
- `BBs`: basic blocks that were covered in total
- `seed`: the current seed
- `fc`: total fuzz cases
- `fcps`: fuzz cases per second
- `cur_loop`: time it took to execute the whole fuzzing loop in µs (includes mutation of input, sending data to target, collecting coverage, and evaluating whether new coverage was discovered)
- `mut_avg`: average time it took to mutate the inputs (in µs)
- `cov_avg`: average time it took to obtain coverage (in µs)
- `corpus`: amount of files currently in the corpus

In general, this really depends on the target, but yeah, `fcps` should ideally be fairly constant. `cur_loop`, `mut_avg`, and `cov_avg` should be as low as possible. `BBs` should be increasing over time, but only if the `corpus` also increases.

**Comment by marcinguy** [comment]
Thank you
